"""answer

Revision ID: 1cf6e624c3bc
Revises: ad48ff8ae2b8
Create Date: 2025-08-21 11:59:24.375670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cf6e624c3bc'
down_revision: Union[str, None] = 'ad48ff8ae2b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('user_id', sa.BIGINT(), nullable=False, comment='User ID'),
    sa.Column('question_code', sa.TEXT(), nullable=False, comment='Question code'),
    sa.Column('answer', sa.TEXT(), nullable=False, comment='Answer text'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False, comment='Временная метка создания записи'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False, comment='Временная метка последнего обновления записи'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_question_code'), 'answer', ['question_code'], unique=False)
    op.create_index(op.f('ix_answer_user_id'), 'answer', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_user_id'), table_name='answer')
    op.drop_index(op.f('ix_answer_question_code'), table_name='answer')
    op.drop_table('answer')
    # ### end Alembic commands ###
