"""Idx

Revision ID: ad48ff8ae2b8
Revises: 8e0e75162540
Create Date: 2025-08-15 11:38:29.572889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad48ff8ae2b8'
down_revision: Union[str, None] = '8e0e75162540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_city'), 'user', ['city'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_city'), table_name='user')
    # ### end Alembic commands ###
