"""Initial migration

Revision ID: 8e0e75162540
Revises: b83cb0f2b8e1
Create Date: 2025-08-14 12:15:41.661697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e0e75162540'
down_revision: Union[str, None] = 'b83cb0f2b8e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('city', sa.TEXT(), nullable=True, comment='City'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'city')
    # ### end Alembic commands ###
