"""wardrobe_ticket

Revision ID: 16091c7f4ec3
Revises: 2cc05e8ca1c8
Create Date: 2025-08-21 18:14:47.961434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16091c7f4ec3'
down_revision: Union[str, None] = '2cc05e8ca1c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('wardrobe_ticket', sa.Integer(), nullable=True, comment='Wardrobe ticket number'))
    op.create_index(op.f('ix_user_wardrobe_ticket'), 'user', ['wardrobe_ticket'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_wardrobe_ticket'), table_name='user')
    op.drop_column('user', 'wardrobe_ticket')
    # ### end Alembic commands ###
