"""wardrobe

Revision ID: 2cc05e8ca1c8
Revises: 1cf6e624c3bc
Create Date: 2025-08-21 18:11:50.091103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cc05e8ca1c8'
down_revision: Union[str, None] = '1cf6e624c3bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wardrobe_ticket',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('ticket', sa.Integer(), nullable=False, comment='Ticket number'),
    sa.Column('is_used', sa.Boolean(), nullable=False, comment='Is used'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wardrobe_ticket_is_used'), 'wardrobe_ticket', ['is_used'], unique=False)
    op.create_index(op.f('ix_wardrobe_ticket_ticket'), 'wardrobe_ticket', ['ticket'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wardrobe_ticket_ticket'), table_name='wardrobe_ticket')
    op.drop_index(op.f('ix_wardrobe_ticket_is_used'), table_name='wardrobe_ticket')
    op.drop_table('wardrobe_ticket')
    # ### end Alembic commands ###
