"""Initial migration

Revision ID: b83cb0f2b8e1
Revises: 
Create Date: 2025-08-14 12:02:11.229662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b83cb0f2b8e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BIGINT(), nullable=False, comment='ID Telegram'),
    sa.Column('first_name', sa.TEXT(), nullable=False, comment='First name'),
    sa.Column('last_name', sa.TEXT(), nullable=True, comment='Last name'),
    sa.Column('username', sa.TEXT(), nullable=True, comment='Username'),
    sa.Column('language_code', sa.TEXT(), nullable=True, comment='Language code'),
    sa.Column('is_admin', sa.Boolean(), nullable=False, comment='Is admin'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False, comment='Временная метка создания записи'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False, comment='Временная метка последнего обновления записи'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Признак удаления'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=True)
    op.create_index(op.f('ix_user_is_admin'), 'user', ['is_admin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_is_admin'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
